### ISSUE TITLE
pipeline_stream_fn.h missing

### ISSUE THREAD

**Issue by devsschmidt** [pipelinedb/pipeline_kafka#16]
hi,

i'm currently trying to compile this extension to add it to my pipelinedb instance but i'm running in a problem neither i nor google seems to be able to solve.

when i execute **make** command i get the following error

`stc@vm:~/pipeline_kafka$ make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -fpic -I. -I./ -I/usr/include/postgresql/9.4/server -I/usr/include/postgresql/internal -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.6  -c -o pipeline_kafka.o pipeline_kafka.c
pipeline_kafka.c:23:40: fatal error: catalog/pipeline_stream_fn.h: No such file or directory
 #include "catalog/pipeline_stream_fn.h"
                                        ^
compilation terminated.
<builtin>: recipe for target 'pipeline_kafka.o' failed
make: *** [pipeline_kafka.o] Error 1
`

does anyone has an idea what to do? I'm running on debian 8.

cheers and thanks in advance

**Comment by usmanm** [comment]
Is `pipeline-config` on your `PATH`? It seems like the PipelineDB header files aren't visible in the shell you're running `make` from.

**Comment by devsschmidt** [comment]
you are right i had a total chaotic approache. but i got it working with a structured step by step approach. you can find my script here 

http://stackoverflow.com/questions/37181225/how-to-build-pipeline-kafka-extension

in case anyone runs into similar problems

**Comment by usmanm** [comment]
Awesome! Thanks for documenting the process!
