### ISSUE TITLE
SELECT kafka_add_broker('localhost:9092') returns function kafka_add_broker(unknown) does not exist

### ISSUE THREAD

**Issue by eterps** [pipelinedb/pipeline_kafka#17]
After following the instructions in https://www.pipelinedb.com/blog/sql-on-kafka
When I execute `SELECT kafka_add_broker('localhost:9092');` in the pipeline console (as suggested by the blog post), I get:

```
pipeline=# SELECT kafka_add_broker('localhost:9092');
ERROR:  function kafka_add_broker(unknown) does not exist
LINE 1: SELECT kafka_add_broker('localhost:9092');
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by usmanm** [comment]
We changed the API a little in version 0.9.1. The function now is `pipeline_kafka.add_broker(host text)`. You can find up-to-date documentation at: http://docs.pipelinedb.com/integrations.html#apache-kafka. I'll update the SQL on Kafka post to reflect that as well.
