### ISSUE TITLE
Memory issue when trying to process JSON data

### ISSUE THREAD

**Issue by uptakechancock** [pipelinedb/pipeline_kafka#24]
I am following the instructions on the blog: https://www.pipelinedb.com/blog/sql-on-kafka. My applications usage is pulling data off of a consumer and getting message counts similar to the blog example.

All the SQL commands from the article execute as expected however after I execute the SQL function pipeline_kafka.consume_begin and then run on the continuous view a select \* I see no results.

I look at my logfile and I consistenty see this error.

ERROR:  out of memory
DETAIL:  Cannot enlarge string buffer containing 1073355686 bytes by 470805 more bytes.
LOG:  worker process: [kafka consumer] quarintine <- ingestion_qa_acm_cat_quarantine (PID 1234) exited with exit code 1
LOG:  [pipeline_kafka consumer] quarintine <- ingestion_qa_acm_cat_quarantine (PID 1243): consuming partition 2 from offset 11109288
LOG:  [pipeline_kafka consumer] quarintine <- ingestion_qa_acm_cat_quarantine (PID 1243): consuming partition 5 from offset 11198570
LOG:  [pipeline_kafka consumer] quarintine <- ingestion_qa_acm_cat_quarantine (PID 1243): consuming partition 4 from offset 11337149
LOG:  [pipeline_kafka consumer] quarintine <- ingestion_qa_acm_cat_quarantine (PID 1243): consuming partition 1 from offset 14139601
LOG:  [pipeline_kafka consumer] quarintine <- ingestion_qa_acm_cat_quarantine (PID 1243): consuming partition 3 from offset 14139606
LOG:  [pipeline_kafka consumer] quarintine <- ingestion_qa_acm_cat_quarantine (PID 1243): consuming partition 0 from offset 11514847
ERROR:  out of memory

When doing some research on copy it says the working theory that the copy command is not able to interpret a certain subset of the data, however when I test this data by running the jq parser I don't see any type of parsing error.

At this point I am at a lost and was wondering if anyone has seen this error.

**Comment by derekjn** [comment]
Thanks for providing additional information on Gittr @uptakechancock. We're looking into this and will report back here when we know what's going on.
- PipelineDB 0.9.3 (AMZN RPM)
- `pipeline_kafka` `master`

**Comment by derekjn** [comment]
What's going on here is that we're not accounting for large messages as well is we should be.

**Comment by uptakechancock** [comment]
So can I understand this a little better... Is this a size limit on any text that is being inserted via copy or is this a size limit when parsing on JSON based data?

Also what is that current limit?

**Comment by uptakechancock** [comment]
Sorry,

When you say that this is a delimeter issue I am a little confused. If you
look at the sample rawdata that I have provided you see something like so.

{"attributes":{"data":"[{\

At this point you see this massive json array of timestamp and value key
pairs. Now the key I can confirm that the array is being fully encapsulated
in [], however at that point there are still a few more attributes in the
message, but the message it self normally ends with the valid json tag of }

So when you say delimiter in regards to JSON nomeclature all messages have
been encapsulated inside {}, anything that is a json array is fully
enscapsulated with [].

I hope all this makes sense in regards to me understanding your observation.

## Please let me know if I can provide any additional information.

Craig Hancock

**Comment by usmanm** [comment]
Hey @uptakechancock, we think the problem wasn't with offsets but `pipeline_kafka` not properly handling very large messages and running out of memory. I just pushed a commit which adds a new configuration parameter `maxbytes` (defaults to 32mb) which forces a `COPY` after either `batchsize` messages have been buffered or `maxbytes` data size has been buffered. Can you re-run your workload and see if this helps?

**Comment by uptakechancock** [comment]
Thank you so much. To confirm the maxbytes option is this passed to the SQL
function SELECT pipeline_kafka.consume_begin

**Comment by usmanm** [comment]
Yes, it's passed to that function. Did this resolve your issue?

**Comment by uptakechancock** [comment]
I just tried this and yes it does resolve my issue I am no longer seeing memory usage issues in my logs.. Just curious thought if you have any recommendation on what to set this too. As you our aware my payload is somewhat large and want to size this data appropriately. I want to try to avoid this consumer getting behind in lagging because this is not sized to handle the current message sizing. 

Lastly what is the default consumer behavior starting at the begining of the topic or at the end if an offset is not specified.

Thanks again for the quick response.

**Comment by usmanm** [comment]
Depends on how much memory your machine has. `pipeline_kafka` could use up to 2x the `maxbytes` memory, so however much spare memory you think you have. You don't want to allocate too much memory and starve other PipelineDB processes or worse start swapping.

The default is from the end. You can change it by specifying the `start_offset`. See [here](http://docs.pipelinedb.com/integrations.html#consuming-messages).
