### ISSUE TITLE
Unable to parse valid Json

### ISSUE THREAD

**Issue by usmanm** [pipelinedb/pipeline_kafka#27]
Hi,

I am evaluating PipelineDB and hooked it up to a Kafka stream generated by golang's marshaller. So far, no tool had any issues with the JSON, however PipelineDB is acting up on JSON like:

```
{"screen": "7\" TFT"}
```

There seems to be double-unescaping going on.

/cc @sixtus

**Comment by derekjn** [comment]
@sixtus I don't think there's any issue here, at least without having more information about how these messages are being produced. We're happy to keep looking at this if you can provide exact repro steps/scripts that we can use on our end to determine if there's a problem or if this is expected behavior.

Also are you referring to the `pipeline_kafka` producer or consumer here?

**Comment by sixtus** [comment]
I am talking about consumer.

Simply put above json into a kafka stream and configure an intake. Should not be very hard to reproduce.

**Comment by sixtus** [comment]
The json is trivial, so it should not matter how they are produced. But if you must now, it's golang's serializer. But I just verified, ruby serializes the string this way too. And it's according to JSON specs.

**Comment by derekjn** [comment]
Hmm, and you're using `json` mode? e.g. something like:

```
SELECT pipeline_kafka.consume_begin('topic', 'stream', format := 'json');
```

If you're not specifying `json` as the format, that's probably the issue here because the default interpretation is `text`.

**Comment by sixtus** [comment]
It's been a while since I ran the test. But since I was following https://www.pipelinedb.com/blog/sql-on-kafka I likely did not do that. You might want to fix up that article, it's the first thing google brings up.

Which is especially confusing as the `->>` operator works w/o `format := 'json'`

**Comment by derekjn** [comment]
>  You might want to fix up that article, it's the first thing google brings up.

Good suggestion, fixed!

> Which is especially confusing as the ->> operator works w/o format := 'json'

The consumer format is actually a bit different than a type, so the `->>` does only actually work on `json` values. So you can consume in `text` format and if your stream is `json`, it will be casted to `json` by the time that operator is applied to it. I can understand how this can be potentially confusing when dealing with only `json` values, but imagine consuming in `text` format when your messages are CSV rows that look something like:

```
0,1.24,some_text
```

When your stream definition looks like this:

```
CREATE STREAM stream (x integer, y float8, z text);
```

So the `format` is only used for interpreting raw data, which will ultimately be casted to the correct underlying types. Hopefully that makes things a bit clearer!
