### ISSUE TITLE
Need help (Can't see any message count on continuous view)

### ISSUE THREAD

**Issue by vinaygulani1** [pipelinedb/pipeline_kafka#41]
Hi,
I am new to pipelinedb, not able to see any message count on continuous view. I have followed the instructions given.
1. Created kafka topic "test" and produced few text messages to it.
2. added broker "localhost:9092" to pipeline_kafka.
SELECT pipeline_kafka.add_broker('localhost:9092');
3. created topic_stream and called consume begin from test topic.
SELECT pipeline_kafka.consume_begin('test', 'topic_stream');
4. created continous view to get the count of stream. 
create continuous view message_count as SELECT Count(*) FROM topic_stream;
5. message_count results 0. (But the messages are available in kafka topic.)
pipeline=# SELECT \* FROM message_count;
## count

(0 rows)

Could you please suggest whether I am missing something or doing something wrong.

Thanks

**Comment by derekjn** [comment]
Hi @vinaygulani1,

By default `consume_begin` will begin consuming only new messages written to Kafka. To consume old messages, you can specify a `start_offset`:

```
SELECT pipeline_kafka.consume_begin('test', 'topic_stream', start_offset := 0);
```

**Comment by vinaygulani1** [comment]
I tested by producing more messages to topic, but still it was showing count as 0. 

This seems to a kafka-version incompatibility. Pipelinedb log says:

LOG:  [pipeline_kafka] topic_stream <- test (PID 2867): librdkafka error: localhost:9092/0: Protocol parse failure at rd_kafka_fetch_reply_handle:3829 (incorrect broker.version.fallback?)

I am using kafka version 0.8.2.2. It seems I need to set "broker.version.fallback" property in librdkafka and rebuild pipeline_kafka.

**Comment by derekjn** [comment]
Try using the `0.8.2.2` branch of `pipeline_kafka`. Then in `pipelinedb.conf`, set

```
pipeline_kafka.broker_version = '0.8.2.2'
```

**Comment by vinaygulani1** [comment]
Using this version is looking for zookeeper_mt library:

```

checking for main in -lzookeeper_mt... no
configure: error: zookeeper_mt
```

**Comment by derekjn** [comment]
If you're on Ubuntu you can install `zookeeper_mt` with:

```
sudo apt-get install zookeeper_mt
```

**Comment by vinaygulani1** [comment]
I am using centos. So could not install using yum. But following this link I was able to install it in centos:
https://apache.googlesource.com/zookeeper/+/refs/heads/trunk/src/c/README

But getting follwing errors on running make command on it:

```
[vagrant@localhost pipeline_kafka]$ make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -g -O2 -fpic -I. -I./ -I/usr/lib/pipelinedb/include/pipelinedb/server -I/usr/lib/pipelinedb/include/pipelinedb/internal -D_GNU_SOURCE   -c -o src/pipeline_kafka.o src/pipeline_kafka.c
src/pipeline_kafka.c:122: warning: initialization makes integer from pointer without a cast
src/pipeline_kafka.c: In function ‘kafka_consume_main’:
src/pipeline_kafka.c:1415: error: ‘rd_kafka_topic_partition_list_t’ undeclared (first use in this function)
src/pipeline_kafka.c:1415: error: (Each undeclared identifier is reported only once
src/pipeline_kafka.c:1415: error: for each function it appears in.)
src/pipeline_kafka.c:1415: error: ‘topics’ undeclared (first use in this function)
src/pipeline_kafka.c:1415: warning: implicit declaration of function ‘rd_kafka_topic_partition_list_new’
src/pipeline_kafka.c:1416: warning: implicit declaration of function ‘rd_kafka_topic_partition_list_add’
src/pipeline_kafka.c:1417: warning: implicit declaration of function ‘rd_kafka_committed’
src/pipeline_kafka.c:1484: warning: implicit declaration of function ‘rd_kafka_consumer_close’
make: *** [src/pipeline_kafka.o] Error 1
```

**Comment by derekjn** [comment]
You need to use a newer version of `librdkafka`. Try `0.9.1`.

**Comment by vinaygulani1** [comment]
Thanks, I am able to install using newer `librdkafka` version.
But, It is now expecting shared object: libzookeeper_mt.so

```
[vagrant@localhost data]$ pipelinedb -D ~/pipelinedb/data/
FATAL:  could not load library "/usr/lib/pipelinedb/lib/pipelinedb/pipeline_kafka.so": libzookeeper_mt.so.2: cannot open shared object file: No such file or directory
```

pipelinedb.conf

```
shared_preload_libraries = 'pipeline_kafka'
pipeline_kafka.broker_version = '0.8.2.2'
```

**Comment by derekjn** [comment]
A few questions:
- Is `libzookeeper_mt` on your system's `LD_LIBRARY_PATH`?
- Did you run `make install` `libzookeeper`?
- Did you run `ldconfig`/`sudo ldconfig` after running `make install` so that your system can see the newly installed library?

**Comment by vinaygulani1** [comment]
Thanks @derekjn, I installed libzookeeper and it worked.

**Comment by derekjn** [comment]
Awesome! Let us know if you need any more help :)
