### ISSUE TITLE
UTC Timestamp doesnt work

### ISSUE THREAD

**Issue by devsschmidt** [pipelinedb/pipeline_kafka#58]
The following continuous view will not contain any data (unless you are already in UTC timezone) since the UTC Parameter doesnt seems to be applied to return value of clock_timestamp(). 

```
CREATE STREAM my_stream(payload JSONB);

CREATE CONTINUOUS VIEW my_count_5_minutes AS 
SELECT COUNT(1) _count
FROM my_stream
WHERE (payload->>'created')::TIMESTAMP> clock_timestamp() AT TIME ZONE 'UTC' - '5  Minutes'::INTERVAL;

```
(Im working in Germany which puts my timezone at +0100 to UTC)
When i add the difference between my timezone and UTC to my interval ('65  Minutes'::INTERVAL)  it works.

What works, but still seems to be a weird solution:
```
CREATE STREAM my_stream(payload JSONB);

CREATE CONTINUOUS VIEW my_count_5_minutes AS 
SELECT COUNT(1) _count
FROM (SELECT payload, (payload->>'created')::TIMESTAMP _created, (clock_timestamp() AT TIME ZONE 'UTC')::TIMESTAMP _utc
            FROM my_stream) AS t 
WHERE _created > _utc - '5  Minutes'::INTERVAL;

```

**Comment by derekjn** [comment]
@devsschmidt thanks for reporting! Do yo mind moving this issue over to https://github.com/pipelinedb/pipelinedb/issues? Thanks!

**Comment by devsschmidt** [comment]
done, issue has been moved
