### ISSUE TITLE
No have group_id in my consume_begin function 

### ISSUE THREAD

**Issue by luizkava** [pipelinedb/pipeline_kafka#65]
After installed the kafka_exetension 0.9.3, the function consume_begin does not appears the group_id option.... 
`pipeline_kafka.consume_begin(topic text, relation text, format text DEFAULT 'text'::text, delimiter text DEFAULT '	'::text, quote text DEFAULT NULL::text, escape text DEFAULT NULL::text, batchsize integer DEFAULT 1000, maxbytes integer DEFAULT 32000000, parallelism integer DEFAULT 1, timeout integer DEFAULT 250, start_offset bigint DEFAULT NULL::bigint)
`

**Comment by luizkava** [comment]
no one ?

**Comment by derekjn** [comment]
@luizkava can you explain a bit more about what the problem you're having? If you installed this over an older version of `pipeline_kafka`, you might want to try dropping `pipeline_kafka` and then recreating it with the latest version installed.

**Comment by luizkava** [comment]
Hi @derekjn , I have 2 servers with the same kafka version (I think), in the first server the function pipeline_kafka.consume_begin doesn't have the variable "group_id"...
How do I know the pipeline_kafka version ?

**Comment by derekjn** [comment]
@luizkava you can check the version by entering `\dx` in a shell. But the problem you're having is that you have different versions of the extension installed, so you should just do a clean install and `CREATE EXTENSION` on each of your servers.

**Comment by luizkava** [comment]
@derekjn I've seen the versions, and it's the same on the servers (0.9.3), but I'll try your suggestion.

**Comment by derekjn** [comment]
@luizkava sounds good. If that doesn't work, just let us know and we'll keep at it until you're up and running.

**Comment by luizkava** [comment]
@derekjn thanks a lot, it's worked... I removed and installed the extension again...

regards.

**Comment by derekjn** [comment]
@luizkava great to hear! Let us know if you need anything else.
