### ISSUE TITLE
pipeline_kafka.consume_begin returns "failure"

### ISSUE THREAD

**Issue by Sudmota** [pipelinedb/pipeline_kafka#66]
I have 3 topics, for all of them I execute:

`
CREATE STREAM <stream_name> (payload json);
SELECT pipeline_kafka.consume_begin('<topic_name>', '<stream_name>', format := 'json')
`

Two of them return "success", one returns "failure".

All queues are defined the same way in kafka.

Any idea of what cases might trigger this "failure" ?

**Comment by luizkava** [comment]
@Sudmota  May you post the code you ran?

**Comment by Sudmota** [comment]
Sure, @luizkava :

```
pipeline=# CREATE STREAM connection_stream (payload json);
CREATE STREAM
pipeline=#
pipeline=# SELECT pipeline_kafka.consume_begin('connection', 'connection_stream', format := 'json');
 consume_begin
---------------
 failure
(1 row)
```

**Comment by luizkava** [comment]
I'm not sure but try put the schema name in front of the stream name...

`SELECT pipeline_kafka.consume_begin('connection', 'pipeline_kafka.connection_stream', format := 'json');`

Did you see the  archive log on the server ?

**Comment by derekjn** [comment]
@Sudmota also, do you see anything in the PipelineDB logs?

**Comment by Sudmota** [comment]
Hey !

My fault, full disk. However, after ensuring that the disks are free, there are no networking issues, I cant subscribe more than 6 topics. However, I can unsubscribe one, to subscribe another, with success. Is there any limitation known (ie free version limitation) regarding this issue ?

**Comment by derekjn** [comment]
> I cant subscribe more than 6 topics.

@Sudmota can you provide more specifics here? e.g. how did the system inform you of this?
