### ISSUE TITLE
PipelineDB 1.0 compatibility

### ISSUE THREAD

**Issue by ikingnet** [pipelinedb/pipeline_kafka#78]

**Comment by derekjn** [comment]
@ikingnet we'll be publishing a `pipeline_kafka` release that supports PipelineDB `1.0.0` early next week. I'll reply here as soon as it's available, there are only a couple of minor changes we need to make.

**Comment by devsschmidt** [comment]
any news on this issue?

**Comment by taojin0505** [comment]
could not install pipeline_kafka on PipelineDB 1.0.
```
[root@db pipeline_kafka]# make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -I. -I./ -I/usr/pgsql-10/include/server -I/usr/pgsql-10/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o pipeline_kafka.o pipeline_kafka.c
pipeline_kafka.c:26:40: fatal error: catalog/pipeline_stream_fn.h: No such file or directory
 #include "catalog/pipeline_stream_fn.h"
                                        ^
compilation terminated.
make: *** [pipeline_kafka.o] Error 1
```

**Comment by sunmatus** [comment]
> @ikingnet we'll be publishing a `pipeline_kafka` release that supports PipelineDB `1.0.0` early next week. I'll reply here as soon as it's available, there are only a couple of minor changes we need to make.

waiting for...

**Comment by iandelahorne** [comment]
I'm curious about this as well, we'd like to update to PipelineDB 1.0 and we use pipeline_kafka

**Comment by derekjn** [comment]
Apologies for the delay here guys--we've been insanely busy with onboarding new customers after the extension release. We're aiming to get `pipeline_kafka with support for PipelineDB `1.0` out this coming week. It requires very little work so it shouldn't be much longer

Thanks for your patience and understanding guys, we're on it!

**Comment by derekjn** [comment]
@ikingnet @devsschmidt @taojin0505 @sunmatus @iandelahorne `pipeline_kafka` is now compatible with PipelineDB core `1.0.0`. You'll want to use the latest release revision:

https://github.com/pipelinedb/pipelinedb/releases/tag/1.0.0-9

Thank you all for your patience on this--our apologies that it took us longer than we would have liked. Let us know if you have any issues running `pipeline_kafka` against PipelineDB `1.0.0`!

**Comment by devsschmidt** [comment]
How can we install pipeline_kafka ? as usualy self build or do we just need to update pipelinedb?

**Comment by devsschmidt** [comment]
btw, wonderful News. i'm very eager to try it.

**Comment by derekjn** [comment]
@devsschmidt `pipeline_kafka` has always required building from source.

**Comment by cailin-lai** [comment]
Very nice! Sounds like I'd schedule the migration works from v0.9.7 (with pipeline_kafka). ;-)
